### ISSUE TITLE
Support removal of key/value pairs

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/jmt#24]
Per [ICS23](https://github.com/cosmos/ibc/tree/master/spec/core/ics-023-vector-commitments#adding--removing-elements), we will want to support removal of key-value pairs.

This functionality doesn't currently exist in the tree implementation; we should figure out whether any changes to the data structures would be required to add it.  For instance, if we remove a key as part of version `v`, we want it to be present for all previous versions, so maybe we need to write a tombstone value into the tree?  Also, how would this work with the existing API, which only supports inserting pairs, if we want to allow a single version to include both insertions and deletions?

**Comment by plaidfinch** [comment]
The attempt in #47 seems to end up with quite a lot of complexity. An alternate approach is to change the *interface* so that `None` values can be set, but not the *internal implementation*: the tree will still contain witnesses for all deleted keys, but the values at those leaves will be `None`.

Outlying design question for this approach: what should the hash of such a leaf be? Should it make it such that the root hash is identical between a tree whose key has been pseudo-deleted in this way, and a tree which never contained that key (assuming all other versions are the same)? Is this even possible? Is it desirable? Is it necessary?

**Comment by hdevalence** [comment]
There are two big downsides to that approach:

1. It means that we can't form Merkle proofs of nonexistence for deleted values. We'd have to produce a proof of existence of a sentinel value, and require every counterparty to understand the sentinel.
2. It means that snapshotting the tree won't be able to save space for deleted values, because the sentinels will still be recorded

**Comment by plaidfinch** [comment]
Implemented in `newmain`.
