### ISSUE TITLE
Implement exclusion proofs and a proof spec that supports ICS-23 nonexistence proofs

### ISSUE THREAD

**Issue by avahowell** [penumbra-zone/jmt#65]
To properly support IBC, we need to implement nonexistence proofs for the JMT. ICS23 currently only supports nonexistence-by-exclusion proofs, where the key path is not hashed. There is a changeset [here](https://github.com/confio/ics23/compare/master...heliaxdev:ics23:yuji/compare_hashed_key) which supports exclusion proof verification with a keyhashed tree, such as the JMT or SMT. This changeset adds two new fields to the ICS23 proof proto, but since proto defaults to 0 for unknown fields, this changeset is backwards compatible. To support JMT ICS23 nonexistence proofs with this, we need to:

- [x] Implement a `get_with_exclusion_proof` method on the JMT that returns an exclusion proof for the requested value if it doesn't exist
- [x] Add code to ics23_impl that can package an exclusion proof into the correct ics23 exclusion proof format.

**Comment by hdevalence** [comment]
On the second point, I think that in order to convert the raw merkle data into ICS23 format, we'll also need to have the full leaf values, since the ICS23 nonexistence proofs supply existence proofs of the left and right leaves.  We can do this in `penumbra_storage` using the index in https://github.com/penumbra-zone/penumbra/issues/1647 , but we'll have to figure out how we want to connect that with the JMT code (which shouldn't assume any extra storage beyond the `TreeReader`/`TreeWriter` interface).

Either we'll need to put the ICS23 nonexistence proof conversion code in `penumbra_storage` (where it can look up the leaf data), or we'll need a way to supply the leaf data in the `jmt` API.

**Comment by conorsch** [comment]
@avahowell Status update? I believe recent Discord discussion indicates this is very close to finished, but I don't want to speak for you.

**Comment by redshiftzero** [comment]
The PoC has been done, so closing!
